# exe member: 引用 greeter lib，演示跨 member 依赖。

[project]
name              = "hello"
kind              = "exe"
entry             = "Hello.main"
version.workspace = true
license.workspace = true

[sources]
include = ["src/**/*.z42"]

[dependencies]
"greeter".workspace = true
