[project]
name    = "z42.compression"
version = "0.1.0"
kind    = "lib"

[dependencies]
"z42.core" = "0.1.0"
"z42.io"   = "0.1.0"   # Std.IO.Stream + MemoryStream for WrapWrite / WrapRead

[tests.dependencies]
"z42.test" = "0.1.0"
