#!/usr/bin/env bash
# scripts/test-vm.sh — Run VM golden tests in interp and/or JIT mode.
#
# Each golden test directory must contain:
#   source.zbc          — compiled bytecode (generated by regen-golden-tests.sh)
#   expected_output.txt — expected stdout
#
# Usage:
#   ./scripts/test-vm.sh                    # rebuild stdlib + golden zbc, then run interp + jit
#   ./scripts/test-vm.sh interp             # interp only
#   ./scripts/test-vm.sh jit               # jit only
#   ./scripts/test-vm.sh --no-rebuild       # skip stdlib + golden rebuild (fast iteration)
#   ./scripts/test-vm.sh interp --no-rebuild
#   ./scripts/test-vm.sh --jobs 8           # run 8 tests concurrently (parallel mode)
#   ./scripts/test-vm.sh interp --no-rebuild --jobs $(nproc)  # fast iteration, all cores
#
# Default behaviour rebuilds stdlib zpkgs (sync to artifacts/build/libs/release/) and golden
# .zbc artifacts before running, eliminating the historical "stale artifact gives
# false GREEN/RED" failure mode (2026-05-04 fix-test-vm-stale-artifacts; previously
# multiple archived commits' "全绿" verification was based on out-of-sync libs/
# zpkg + old golden zbc emitted by an earlier compiler version).
#
# Exit code: 0 if all selected tests pass, 1 otherwise.

set -euo pipefail

# Resolve project root regardless of working directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
cd "$ROOT"

RUNTIME_MANIFEST="src/runtime/Cargo.toml"
# Test roots (dotnet/runtime-style):
#   src/tests/<category>/<name>/         — VM e2e by feature category
#   src/libraries/<lib>/tests/<name>/    — stdlib-specific cases (no golden/ middle)
GOLDEN_GLOBS=(
    "src/tests/"*"/"*"/"
    "src/libraries/"*"/tests/"*"/"
)
MODES=("interp" "jit")

REBUILD=true
JOBS=1
POSITIONAL=()
for arg in "$@"; do
    case "$arg" in
        --no-rebuild)  REBUILD=false ;;
        --jobs=*)      JOBS="${arg#--jobs=}" ;;
        --jobs|-j)     echo "error: --jobs requires a value (e.g. --jobs=4)" >&2; exit 2 ;;
        -j[0-9]*)      JOBS="${arg#-j}" ;;
        *)             POSITIONAL+=("$arg") ;;
    esac
done

if [ "${#POSITIONAL[@]}" -ge 1 ]; then
    MODES=("${POSITIONAL[0]}")
fi

if [ "$REBUILD" = true ]; then
    # Order matters: regen-golden-tests.sh internally calls build-stdlib.sh
    # (transitively rebuilds the C# compiler driver), then recompiles every
    # golden source.z42 → source.zbc against the freshly-built stdlib zpkgs
    # synced into artifacts/build/libs/release/. Pass through to keep both step's
    # output streams visible.
    "$SCRIPT_DIR/regen-golden-tests.sh"
    echo ""
fi

# Build VM once. The target-dir is set to artifacts/build/runtime via
# .cargo/config.toml, so the binary is always at the path below. Using
# the binary directly (not `cargo run`) avoids per-test cargo overhead
# (~100 ms per invocation) and eliminates cargo-lock contention in
# parallel mode.
echo "Building VM..."
cargo build -q --manifest-path "$RUNTIME_MANIFEST"
# Also build the z42-compression cdylib — z42vm dlopens it at startup for
# `__compressor_*` natives. The main `cargo build` above only emits the
# rlib via the dependency graph; `crate-type = ["cdylib", ...]` outputs
# (`libz42_compression.dylib` etc.) are produced only when the
# z42-compression crate is the workspace root of a `cargo build`
# invocation. JIT mode pre-resolves all builtins at compile time, so
# missing this dylib makes every JIT golden test panic with `unknown
# builtin __compressor_begin`.
cargo build -q --manifest-path "$ROOT/src/runtime/crates/z42-compression/Cargo.toml"
VM_BIN="$ROOT/artifacts/build/runtime/debug/z42vm"
if [[ ! -x "$VM_BIN" ]]; then
    echo "error: VM binary not found at $VM_BIN after cargo build" >&2
    exit 1
fi
echo ""

OVERALL_PASS=0
OVERALL_FAIL=0

for MODE in "${MODES[@]}"; do
    echo "══════════════════════════════════════"
    echo " Mode: $MODE"
    echo "══════════════════════════════════════"

    PASS=0
    FAIL=0
    FAILURES=()

    # Enumerate cases in two layouts:
    #   Dir mode:  <root>/<name>/source.zbc + <root>/<name>/expected_output.txt
    #   Flat mode: <root>/<name>.zbc        + <root>/<name>.expected_output.txt (rare; usually absent = assert-only)
    # CASES tuples: "name|artifact|expected|interp_only_marker"
    CASES=()
    # Derive entry name from .z42 source. Priority mirrors C# GoldenTests:
    #   *.Main > Main > *.main > main
    # where *. is the optional `namespace X;` prefix. Required since
    # 2026-05-14 (`drop vm::resolve_entry fallback chain`) — raw .zbc files
    # carry no META.entry so the VM no longer guesses.
    derive_entry() {
        local src="$1"
        [ -f "$src" ] || { echo "Main"; return; }
        local ns
        ns=$(grep -m1 '^[[:space:]]*namespace[[:space:]]' "$src" \
             | sed -E 's/^[[:space:]]*namespace[[:space:]]+([A-Za-z_][A-Za-z0-9_.]*)[[:space:]]*;.*/\1/')
        local has_upper has_lower
        has_upper=$(grep -c '\bvoid[[:space:]]\+Main[[:space:]]*(' "$src" || true)
        has_lower=$(grep -c '\bvoid[[:space:]]\+main[[:space:]]*(' "$src" || true)
        local fn
        if [ "$has_upper" -gt 0 ]; then fn="Main";
        elif [ "$has_lower" -gt 0 ]; then fn="main";
        else fn="Main"; fi
        if [ -n "$ns" ]; then echo "$ns.$fn"; else echo "$fn"; fi
    }

    # Exclude wire-format fixture directories — those .z42 files are golden
    # inputs for ZbcWriter / ZpkgWriter byte-level tests (see Z42.Tests.Zbc /
    # Z42.Tests.Zpkg FormatGoldenTests in C#), not runnable cases.
    #
    # The two `gc/composite_ref_weak_mode` + `delegates/multicast_subscription_refs`
    # entries are skipped because they exercise the known-deferred cross-zpkg
    # static field initialization bug (see roadmap.md "Deferred Backlog Index"
    # → 跨包 static field 初始化时机). They fail at runtime with
    # "bitwise op requires integral operands, got Null and Null" because
    # `ModeFlags.Once` / `ModeFlags.Weak` from z42.core are observed as Null
    # before the cross-zpkg static-init pass runs. Will re-enable once that
    # backlog item ships.
    is_excluded_path() {
        case "$1" in
            *src/tests/cross-zpkg/*) return 0 ;;
            *src/tests/zbc-format/*) return 0 ;;
            *src/tests/zpkg-format/*) return 0 ;;
            *src/tests/gc/composite_ref_weak_mode/*) return 0 ;;
            *src/tests/delegates/multicast_subscription_refs/*) return 0 ;;
            *) return 1 ;;
        esac
    }

    for glob in "${GOLDEN_GLOBS[@]}"; do
        for d in $glob; do
            [ -d "$d" ] || continue
            is_excluded_path "$d/" && continue
            [ -f "$d/source.zbc" ] || continue
            name=$(basename "$d")
            entry_name=$(derive_entry "$d/source.z42")
            CASES+=("$name|$d/source.zbc|$d/expected_output.txt|$d/interp_only|$entry_name")
        done
    done
    # Flat mode: only src/tests/ — src/libraries/<lib>/tests/*.zbc belongs to
    # the z42-test-runner (test-stdlib.sh), not the golden runner.
    for f in "src/tests/"*"/"*".zbc"; do
        [ -f "$f" ] || continue
        is_excluded_path "$f" && continue
        name=$(basename "$f" .zbc)
        dir=$(dirname "$f")
        # Flat mode source: same name minus .zbc
        src_file="${f%.zbc}.z42"
        entry_name=$(derive_entry "$src_file")
        CASES+=("$name|$f|$dir/$name.expected_output.txt|$dir/$name.interp_only|$entry_name")
    done

    # Bash 3.2 (macOS native) errors on `"${arr[@]}"` of a declared-but-empty
    # array under `set -u`. Guard the count + fail loudly so a missing-regen
    # config doesn't surface as the cryptic "CASES[@]: unbound variable".
    if [ "${#CASES[@]}" -eq 0 ]; then
        echo "❌ no runnable golden fixtures found." >&2
        echo "   Hint: run \`./scripts/regen-golden-tests.sh\` to produce" >&2
        echo "   src/tests/**/source.zbc and src/libraries/*/tests/**/source.zbc." >&2
        echo "   (test-vm.sh --no-rebuild assumes regen ran previously.)" >&2
        exit 1
    fi

    # Filter cases for this mode (removes interp_only entries when running JIT).
    mode_cases=()
    for entry in "${CASES[@]}"; do
        IFS='|' read -r name artifact expected interp_marker entry_name <<< "$entry"
        if [ "$MODE" = "jit" ] && [ -f "$interp_marker" ]; then
            continue
        fi
        mode_cases+=("$entry")
    done

    # run_one_case: execute a single test case and emit PASS/FAIL output.
    # Non-zero exit if the test fails.
    run_one_case() {
        local entry="$1" mode="$2"
        local name artifact expected interp_marker entry_name
        IFS='|' read -r name artifact expected interp_marker entry_name <<< "$entry"

        local actual expected_str=""
        actual=$("$VM_BIN" "$artifact" "$entry_name" --mode "$mode" 2>&1) || true
        [ -f "$expected" ] && expected_str=$(cat "$expected")

        if [ "$actual" = "$expected_str" ]; then
            return 0
        else
            echo "  FAIL: $name"
            if [ -f "$expected" ]; then
                echo "    expected: $(head -1 "$expected")"
            else
                echo "    expected: <empty>"
            fi
            echo "    actual:   $(echo "$actual" | head -1)"
            return 1
        fi
    }

    if [[ "$JOBS" -le 1 ]]; then
        # ── Sequential ────────────────────────────────────────────────────────
        for entry in "${mode_cases[@]}"; do
            if run_one_case "$entry" "$MODE"; then
                PASS=$((PASS + 1))
            else
                FAIL=$((FAIL + 1))
                IFS='|' read -r name _ <<< "$entry"
                FAILURES+=("$name")
            fi
        done
    else
        # ── Parallel: batches of JOBS cases ───────────────────────────────────
        # Each job captures stdout to a temp file; we print in original order
        # after the batch completes so output stays readable.
        local TMPDIR_VM
        TMPDIR_VM=$(mktemp -d)
        trap 'rm -rf "$TMPDIR_VM"' RETURN

        local n_cases=${#mode_cases[@]}
        local i=0
        while [[ $i -lt $n_cases ]]; do
            local batch_pids=() batch_outs=() batch_rcs=() batch_entries=()

            for ((j = 0; j < JOBS && i + j < n_cases; j++)); do
                local entry="${mode_cases[$((i + j))]}"
                local out_f rc_f
                out_f=$(mktemp "$TMPDIR_VM/out.XXXXXX")
                rc_f=$(mktemp "$TMPDIR_VM/rc.XXXXXX")
                echo "1" > "$rc_f"

                (
                    if run_one_case "$entry" "$MODE"; then
                        echo "0" > "$rc_f"
                    else
                        echo "1" > "$rc_f"
                    fi
                ) > "$out_f" 2>&1 &

                batch_pids+=($!)
                batch_outs+=("$out_f")
                batch_rcs+=("$rc_f")
                batch_entries+=("$entry")
            done

            for pid in "${batch_pids[@]}"; do
                wait "$pid" 2>/dev/null || true
            done

            for k in "${!batch_entries[@]}"; do
                cat "${batch_outs[$k]}"
                rc=$(cat "${batch_rcs[$k]}" 2>/dev/null || echo "1")
                if [[ "$rc" == "0" ]]; then
                    PASS=$((PASS + 1))
                else
                    FAIL=$((FAIL + 1))
                    IFS='|' read -r name _ <<< "${batch_entries[$k]}"
                    FAILURES+=("$name")
                fi
            done

            i=$((i + JOBS))
        done
    fi

    echo ""
    echo "  Result: $PASS passed, $FAIL failed"
    echo ""

    OVERALL_PASS=$((OVERALL_PASS + PASS))
    OVERALL_FAIL=$((OVERALL_FAIL + FAIL))
done

echo "══════════════════════════════════════"
echo " Total: $OVERALL_PASS passed, $OVERALL_FAIL failed"
echo "══════════════════════════════════════"

[ "$OVERALL_FAIL" -eq 0 ]
