#!/usr/bin/env bash
# scripts/test-vm.sh — Run VM golden tests in interp and/or JIT mode.
#
# Each golden test directory must contain:
#   source.zbc          — compiled bytecode (generated by regen-golden-tests.sh)
#   expected_output.txt — expected stdout
#
# Usage:
#   ./scripts/test-vm.sh                    # rebuild stdlib + golden zbc, then run interp + jit
#   ./scripts/test-vm.sh interp             # interp only
#   ./scripts/test-vm.sh jit                # jit only
#   ./scripts/test-vm.sh --no-rebuild       # skip stdlib + golden rebuild (fast iteration)
#   ./scripts/test-vm.sh interp --no-rebuild
#
# Default behaviour rebuilds stdlib zpkgs (sync to artifacts/z42/libs/) and golden
# .zbc artifacts before running, eliminating the historical "stale artifact gives
# false GREEN/RED" failure mode (2026-05-04 fix-test-vm-stale-artifacts; previously
# multiple archived commits' "全绿" verification was based on out-of-sync libs/
# zpkg + old golden zbc emitted by an earlier compiler version).
#
# Exit code: 0 if all selected tests pass, 1 otherwise.

set -euo pipefail

# Resolve project root regardless of working directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
cd "$ROOT"

RUNTIME_MANIFEST="src/runtime/Cargo.toml"
# Test roots (dotnet/runtime-style):
#   src/tests/<category>/<name>/         — VM e2e by feature category
#   src/libraries/<lib>/tests/<name>/    — stdlib-specific cases (no golden/ middle)
GOLDEN_GLOBS=(
    "src/tests/"*"/"*"/"
    "src/libraries/"*"/tests/"*"/"
)
MODES=("interp" "jit")

REBUILD=true
POSITIONAL=()
for arg in "$@"; do
    case "$arg" in
        --no-rebuild) REBUILD=false ;;
        *)            POSITIONAL+=("$arg") ;;
    esac
done

if [ "${#POSITIONAL[@]}" -ge 1 ]; then
    MODES=("${POSITIONAL[0]}")
fi

if [ "$REBUILD" = true ]; then
    # Order matters: regen-golden-tests.sh internally calls build-stdlib.sh
    # (transitively rebuilds the C# compiler driver), then recompiles every
    # golden source.z42 → source.zbc against the freshly-built stdlib zpkgs
    # synced into artifacts/z42/libs/. Pass through to keep both step's
    # output streams visible.
    "$SCRIPT_DIR/regen-golden-tests.sh"
    echo ""
fi

# Build once before running tests
echo "Building VM..."
cargo build -q --manifest-path "$RUNTIME_MANIFEST"
echo ""

OVERALL_PASS=0
OVERALL_FAIL=0

for MODE in "${MODES[@]}"; do
    echo "══════════════════════════════════════"
    echo " Mode: $MODE"
    echo "══════════════════════════════════════"

    PASS=0
    FAIL=0
    FAILURES=()

    # Collect every golden case dir matching any configured glob.
    DIRS=()
    for glob in "${GOLDEN_GLOBS[@]}"; do
        for d in $glob; do
            [ -d "$d" ] && DIRS+=("$d")
        done
    done

    for dir in "${DIRS[@]}"; do
        name=$(basename "$dir")
        artifact="$dir/source.zbc"
        expected="$dir/expected_output.txt"

        # Exclude categories that aren't run-tests:
        case "$dir" in
            src/tests/errors/*|src/tests/parse/*|src/tests/cross-zpkg/*) continue ;;
        esac

        [ -f "$artifact" ] || continue

        # Skip JIT for tests with `interp_only` marker (e.g. tests using IR
        # opcodes whose JIT path is not yet implemented — see closure.md §6).
        if [ "$MODE" = "jit" ] && [ -f "$dir/interp_only" ]; then
            continue
        fi

        actual=$(cargo run -q --manifest-path "$RUNTIME_MANIFEST" -- "$artifact" --mode "$MODE" 2>&1) || true

        # If no expected_output.txt: assertion-based test (Assert.Equal etc.) —
        # success means the VM ran to completion with empty stdout.
        expected_str=""
        [ -f "$expected" ] && expected_str=$(cat "$expected")

        if [ "$actual" = "$expected_str" ]; then
            PASS=$((PASS + 1))
        else
            FAIL=$((FAIL + 1))
            FAILURES+=("$name")
            echo "  FAIL: $name"
            if [ -f "$expected" ]; then
                echo "    expected: $(head -1 "$expected")"
            else
                echo "    expected: <empty>"
            fi
            echo "    actual:   $(echo "$actual" | head -1)"
        fi
    done

    echo ""
    echo "  Result: $PASS passed, $FAIL failed"
    echo ""

    OVERALL_PASS=$((OVERALL_PASS + PASS))
    OVERALL_FAIL=$((OVERALL_FAIL + FAIL))
done

echo "══════════════════════════════════════"
echo " Total: $OVERALL_PASS passed, $OVERALL_FAIL failed"
echo "══════════════════════════════════════"

[ "$OVERALL_FAIL" -eq 0 ]
